version: '3.8'

services:
  bank-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bank-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - bank-backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080 