spring:
  profiles:
    include:
      - secret
  application:
    name: bank
  datasource:
    url: jdbc:h2:mem:bank_transaction_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.cache: DEBUG
    com.ywang.bank: DEBUG

# CORS Configuration
cors:
  allowed-origins:
    - ${FRONTEND_URL:http://localhost:3000}
    - ${FRONTEND_URL_ALT:http://127.0.0.1:3000}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: ${CORS_MAX_AGE:3600}

# Cache Configuration
cache:
  guava:
    max-size: ${CACHE_MAX_SIZE:1000}
    expire-after-write: ${CACHE_EXPIRE_AFTER_WRITE:30}
    expire-after-access: ${CACHE_EXPIRE_AFTER_ACCESS:10}
    record-stats: ${CACHE_RECORD_STATS:true}

